//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int id { get; set; }
        public string content { get; set; }
        public Nullable<int> eventId { get; set; }
        public string author { get; set; }
    
        public virtual User User { get; set; }
        public virtual Event Event { get; set; }
    }
}
