//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.Comments = new HashSet<Comment>();
            this.Notifications = new HashSet<Notification>();
            this.Photos = new HashSet<Photo>();
            this.UserEventAttendants = new HashSet<UserEventAttendant>();
            this.Tags = new HashSet<Tag>();
        }
    
        public int id { get; set; }
        public System.DateTime beginTime { get; set; }
        public System.DateTime endTime { get; set; }
        public string description { get; set; }
        public byte[] thumbnail { get; set; }
        public string title { get; set; }
        public int location { get; set; }
        public string username { get; set; }
        public Nullable<System.DateTime> publishDate { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Location Location1 { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<Photo> Photos { get; set; }
        public virtual ICollection<UserEventAttendant> UserEventAttendants { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
    }
}
