//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interest
    {
        public Interest()
        {
            this.Individuals = new HashSet<Individual>();
        }
    
        public string name { get; set; }
        public string description { get; set; }
        public byte[] thumbnail { get; set; }
    
        public virtual ICollection<Individual> Individuals { get; set; }
    }
}
