//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class EVENetEntities : DbContext
    {
        public EVENetEntities()
            : base("name=EVENetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admins { get; set; }
        public DbSet<Comment> Comments { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<Individual> Individuals { get; set; }
        public DbSet<Interest> Interests { get; set; }
        public DbSet<Location> Locations { get; set; }
        public DbSet<Notification> Notifications { get; set; }
        public DbSet<Organization> Organizations { get; set; }
        public DbSet<Photo> Photos { get; set; }
        public DbSet<Tag> Tags { get; set; }
        public DbSet<Type> Types { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserEventAttendant> UserEventAttendants { get; set; }
    
        public virtual int addComennt(Nullable<int> eventId, string author, string content)
        {
            var eventIdParameter = eventId.HasValue ?
                new ObjectParameter("eventId", eventId) :
                new ObjectParameter("eventId", typeof(int));
    
            var authorParameter = author != null ?
                new ObjectParameter("author", author) :
                new ObjectParameter("author", typeof(string));
    
            var contentParameter = content != null ?
                new ObjectParameter("content", content) :
                new ObjectParameter("content", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addComennt", eventIdParameter, authorParameter, contentParameter);
        }
    
        public virtual int attachInterest(string username, string interest)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var interestParameter = interest != null ?
                new ObjectParameter("interest", interest) :
                new ObjectParameter("interest", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("attachInterest", usernameParameter, interestParameter);
        }
    
        public virtual int attachTag(string tag, Nullable<int> eventId)
        {
            var tagParameter = tag != null ?
                new ObjectParameter("tag", tag) :
                new ObjectParameter("tag", typeof(string));
    
            var eventIdParameter = eventId.HasValue ?
                new ObjectParameter("eventId", eventId) :
                new ObjectParameter("eventId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("attachTag", tagParameter, eventIdParameter);
        }
    
        public virtual int createEvent(Nullable<System.DateTime> beginTime, Nullable<System.DateTime> endTime, string description, byte[] thumbnail, string title, Nullable<int> location, string currentUser)
        {
            var beginTimeParameter = beginTime.HasValue ?
                new ObjectParameter("beginTime", beginTime) :
                new ObjectParameter("beginTime", typeof(System.DateTime));
    
            var endTimeParameter = endTime.HasValue ?
                new ObjectParameter("endTime", endTime) :
                new ObjectParameter("endTime", typeof(System.DateTime));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var thumbnailParameter = thumbnail != null ?
                new ObjectParameter("thumbnail", thumbnail) :
                new ObjectParameter("thumbnail", typeof(byte[]));
    
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var locationParameter = location.HasValue ?
                new ObjectParameter("location", location) :
                new ObjectParameter("location", typeof(int));
    
            var currentUserParameter = currentUser != null ?
                new ObjectParameter("currentUser", currentUser) :
                new ObjectParameter("currentUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("createEvent", beginTimeParameter, endTimeParameter, descriptionParameter, thumbnailParameter, titleParameter, locationParameter, currentUserParameter);
        }
    
        public virtual int createIndividual(string username, string password, byte[] profilePicture, string firstName, string midName, string lastName, Nullable<System.DateTime> dob, Nullable<bool> gender)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var profilePictureParameter = profilePicture != null ?
                new ObjectParameter("profilePicture", profilePicture) :
                new ObjectParameter("profilePicture", typeof(byte[]));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("firstName", firstName) :
                new ObjectParameter("firstName", typeof(string));
    
            var midNameParameter = midName != null ?
                new ObjectParameter("midName", midName) :
                new ObjectParameter("midName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("lastName", lastName) :
                new ObjectParameter("lastName", typeof(string));
    
            var dobParameter = dob.HasValue ?
                new ObjectParameter("dob", dob) :
                new ObjectParameter("dob", typeof(System.DateTime));
    
            var genderParameter = gender.HasValue ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("createIndividual", usernameParameter, passwordParameter, profilePictureParameter, firstNameParameter, midNameParameter, lastNameParameter, dobParameter, genderParameter);
        }
    
        public virtual int createInterest(string name, string description, byte[] thumbnail)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var thumbnailParameter = thumbnail != null ?
                new ObjectParameter("thumbnail", thumbnail) :
                new ObjectParameter("thumbnail", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("createInterest", nameParameter, descriptionParameter, thumbnailParameter);
        }
    
        public virtual int createLocation(string name, string description, string address, Nullable<float> @long, Nullable<float> lat, byte[] thumbnail)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var longParameter = @long.HasValue ?
                new ObjectParameter("long", @long) :
                new ObjectParameter("long", typeof(float));
    
            var latParameter = lat.HasValue ?
                new ObjectParameter("lat", lat) :
                new ObjectParameter("lat", typeof(float));
    
            var thumbnailParameter = thumbnail != null ?
                new ObjectParameter("thumbnail", thumbnail) :
                new ObjectParameter("thumbnail", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("createLocation", nameParameter, descriptionParameter, addressParameter, longParameter, latParameter, thumbnailParameter);
        }
    
        public virtual int createOrganization(string username, string password, byte[] profilePicture, string description, string type, string phone, string website)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var profilePictureParameter = profilePicture != null ?
                new ObjectParameter("profilePicture", profilePicture) :
                new ObjectParameter("profilePicture", typeof(byte[]));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var websiteParameter = website != null ?
                new ObjectParameter("website", website) :
                new ObjectParameter("website", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("createOrganization", usernameParameter, passwordParameter, profilePictureParameter, descriptionParameter, typeParameter, phoneParameter, websiteParameter);
        }
    
        public virtual int createRoot(string username, string password, byte[] profilePicture)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var profilePictureParameter = profilePicture != null ?
                new ObjectParameter("profilePicture", profilePicture) :
                new ObjectParameter("profilePicture", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("createRoot", usernameParameter, passwordParameter, profilePictureParameter);
        }
    
        public virtual int createTag(string tagName)
        {
            var tagNameParameter = tagName != null ?
                new ObjectParameter("tagName", tagName) :
                new ObjectParameter("tagName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("createTag", tagNameParameter);
        }
    
        public virtual int createType(string name, string currentUser)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var currentUserParameter = currentUser != null ?
                new ObjectParameter("currentUser", currentUser) :
                new ObjectParameter("currentUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("createType", nameParameter, currentUserParameter);
        }
    
        public virtual int createUser(string username, string password, byte[] profilePicture, Nullable<int> userType)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var profilePictureParameter = profilePicture != null ?
                new ObjectParameter("profilePicture", profilePicture) :
                new ObjectParameter("profilePicture", typeof(byte[]));
    
            var userTypeParameter = userType.HasValue ?
                new ObjectParameter("userType", userType) :
                new ObjectParameter("userType", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("createUser", usernameParameter, passwordParameter, profilePictureParameter, userTypeParameter);
        }
    
        public virtual int decreaseTagOccurence(string tagName)
        {
            var tagNameParameter = tagName != null ?
                new ObjectParameter("tagName", tagName) :
                new ObjectParameter("tagName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("decreaseTagOccurence", tagNameParameter);
        }
    
        public virtual int deleteComment(string currentUser, Nullable<int> commentId)
        {
            var currentUserParameter = currentUser != null ?
                new ObjectParameter("currentUser", currentUser) :
                new ObjectParameter("currentUser", typeof(string));
    
            var commentIdParameter = commentId.HasValue ?
                new ObjectParameter("commentId", commentId) :
                new ObjectParameter("commentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteComment", currentUserParameter, commentIdParameter);
        }
    
        public virtual int deleteEvent(Nullable<int> id, string username)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteEvent", idParameter, usernameParameter);
        }
    
        public virtual int deleteInterest(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteInterest", nameParameter);
        }
    
        public virtual int detachTag(string tag, Nullable<int> eventId)
        {
            var tagParameter = tag != null ?
                new ObjectParameter("tag", tag) :
                new ObjectParameter("tag", typeof(string));
    
            var eventIdParameter = eventId.HasValue ?
                new ObjectParameter("eventId", eventId) :
                new ObjectParameter("eventId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("detachTag", tagParameter, eventIdParameter);
        }
    
        public virtual int dettachInterest(string username, string interest)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var interestParameter = interest != null ?
                new ObjectParameter("interest", interest) :
                new ObjectParameter("interest", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dettachInterest", usernameParameter, interestParameter);
        }
    
        public virtual int disinvite(Nullable<int> eventId, string username)
        {
            var eventIdParameter = eventId.HasValue ?
                new ObjectParameter("eventId", eventId) :
                new ObjectParameter("eventId", typeof(int));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("disinvite", eventIdParameter, usernameParameter);
        }
    
        public virtual int editLocation(Nullable<int> eventId, Nullable<int> newLocation)
        {
            var eventIdParameter = eventId.HasValue ?
                new ObjectParameter("eventId", eventId) :
                new ObjectParameter("eventId", typeof(int));
    
            var newLocationParameter = newLocation.HasValue ?
                new ObjectParameter("newLocation", newLocation) :
                new ObjectParameter("newLocation", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("editLocation", eventIdParameter, newLocationParameter);
        }
    
        public virtual int follow(string @this, string friend)
        {
            var thisParameter = @this != null ?
                new ObjectParameter("this", @this) :
                new ObjectParameter("this", typeof(string));
    
            var friendParameter = friend != null ?
                new ObjectParameter("friend", friend) :
                new ObjectParameter("friend", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("follow", thisParameter, friendParameter);
        }
    
        public virtual ObjectResult<followerList_Result> followerList(string @this)
        {
            var thisParameter = @this != null ?
                new ObjectParameter("this", @this) :
                new ObjectParameter("this", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<followerList_Result>("followerList", thisParameter);
        }
    
        public virtual ObjectResult<followingList_Result> followingList(string @this)
        {
            var thisParameter = @this != null ?
                new ObjectParameter("this", @this) :
                new ObjectParameter("this", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<followingList_Result>("followingList", thisParameter);
        }
    
        public virtual ObjectResult<getComments_Result> getComments(Nullable<int> eventId)
        {
            var eventIdParameter = eventId.HasValue ?
                new ObjectParameter("eventId", eventId) :
                new ObjectParameter("eventId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getComments_Result>("getComments", eventIdParameter);
        }
    
        public virtual ObjectResult<getInterest_Result> getInterest(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getInterest_Result>("getInterest", nameParameter);
        }
    
        public virtual int increaseTagOccurence(string tagName)
        {
            var tagNameParameter = tagName != null ?
                new ObjectParameter("tagName", tagName) :
                new ObjectParameter("tagName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("increaseTagOccurence", tagNameParameter);
        }
    
        public virtual int invite(Nullable<int> eventId, string username)
        {
            var eventIdParameter = eventId.HasValue ?
                new ObjectParameter("eventId", eventId) :
                new ObjectParameter("eventId", typeof(int));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("invite", eventIdParameter, usernameParameter);
        }
    
        public virtual ObjectResult<listInvitedEvents_Result> listInvitedEvents(string user, Nullable<int> status)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listInvitedEvents_Result>("listInvitedEvents", userParameter, statusParameter);
        }
    
        public virtual ObjectResult<listInvitedPeople_Result> listInvitedPeople(Nullable<int> eventId, Nullable<int> status)
        {
            var eventIdParameter = eventId.HasValue ?
                new ObjectParameter("eventId", eventId) :
                new ObjectParameter("eventId", typeof(int));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listInvitedPeople_Result>("listInvitedPeople", eventIdParameter, statusParameter);
        }
    
        public virtual int respondInvitation(string user, Nullable<int> @event, Nullable<int> decision)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            var eventParameter = @event.HasValue ?
                new ObjectParameter("event", @event) :
                new ObjectParameter("event", typeof(int));
    
            var decisionParameter = decision.HasValue ?
                new ObjectParameter("decision", decision) :
                new ObjectParameter("decision", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("respondInvitation", userParameter, eventParameter, decisionParameter);
        }
    
        public virtual ObjectResult<searchInterestFromName_Result> searchInterestFromName(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<searchInterestFromName_Result>("searchInterestFromName", nameParameter);
        }
    
        public virtual ObjectResult<searchTopTags_Result> searchTopTags(string tagName, Nullable<int> n)
        {
            var tagNameParameter = tagName != null ?
                new ObjectParameter("tagName", tagName) :
                new ObjectParameter("tagName", typeof(string));
    
            var nParameter = n.HasValue ?
                new ObjectParameter("n", n) :
                new ObjectParameter("n", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<searchTopTags_Result>("searchTopTags", tagNameParameter, nParameter);
        }
    
        public virtual ObjectResult<searchUserFromInterest_Result> searchUserFromInterest(string interest)
        {
            var interestParameter = interest != null ?
                new ObjectParameter("interest", interest) :
                new ObjectParameter("interest", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<searchUserFromInterest_Result>("searchUserFromInterest", interestParameter);
        }
    
        public virtual int setEvent(Nullable<int> id, string username, Nullable<System.DateTime> begintime, Nullable<System.DateTime> endtime, string description, byte[] thumbnail, string title, Nullable<int> location)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var begintimeParameter = begintime.HasValue ?
                new ObjectParameter("begintime", begintime) :
                new ObjectParameter("begintime", typeof(System.DateTime));
    
            var endtimeParameter = endtime.HasValue ?
                new ObjectParameter("endtime", endtime) :
                new ObjectParameter("endtime", typeof(System.DateTime));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var thumbnailParameter = thumbnail != null ?
                new ObjectParameter("thumbnail", thumbnail) :
                new ObjectParameter("thumbnail", typeof(byte[]));
    
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var locationParameter = location.HasValue ?
                new ObjectParameter("location", location) :
                new ObjectParameter("location", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("setEvent", idParameter, usernameParameter, begintimeParameter, endtimeParameter, descriptionParameter, thumbnailParameter, titleParameter, locationParameter);
        }
    
        public virtual int setPassword(string username, string oldPassword, string newPassword)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var oldPasswordParameter = oldPassword != null ?
                new ObjectParameter("oldPassword", oldPassword) :
                new ObjectParameter("oldPassword", typeof(string));
    
            var newPasswordParameter = newPassword != null ?
                new ObjectParameter("newPassword", newPassword) :
                new ObjectParameter("newPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("setPassword", usernameParameter, oldPasswordParameter, newPasswordParameter);
        }
    
        public virtual int setProfilePicture(string username, byte[] image)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var imageParameter = image != null ?
                new ObjectParameter("image", image) :
                new ObjectParameter("image", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("setProfilePicture", usernameParameter, imageParameter);
        }
    
        public virtual int unfollow(string @this, string friend)
        {
            var thisParameter = @this != null ?
                new ObjectParameter("this", @this) :
                new ObjectParameter("this", typeof(string));
    
            var friendParameter = friend != null ?
                new ObjectParameter("friend", friend) :
                new ObjectParameter("friend", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("unfollow", thisParameter, friendParameter);
        }
    }
}
