//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int id { get; set; }
        public string receiver { get; set; }
        public string sender { get; set; }
        public Nullable<int> eventId { get; set; }
        public Nullable<int> typeInfo { get; set; }
        public Nullable<bool> Seen { get; set; }
        public Nullable<System.DateTime> timeSent { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
