//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public string username { get; set; }
        public string description { get; set; }
        public string type { get; set; }
        public string phone { get; set; }
        public string website { get; set; }
    
        public virtual Type Type1 { get; set; }
        public virtual User User { get; set; }
    }
}
