//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEventAttendant
    {
        public string username { get; set; }
        public int @event { get; set; }
        public int attend { get; set; }
    
        public virtual Event Event1 { get; set; }
        public virtual User User { get; set; }
    }
}
