//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Comments = new HashSet<Comment>();
            this.Events = new HashSet<Event>();
            this.Notifications = new HashSet<Notification>();
            this.Notifications1 = new HashSet<Notification>();
            this.UserEventAttendants = new HashSet<UserEventAttendant>();
            this.User1 = new HashSet<User>();
            this.Users = new HashSet<User>();
        }
    
        public string username { get; set; }
        public string password { get; set; }
        public byte[] profilePicture { get; set; }
        public System.DateTime registerDate { get; set; }
        public int userType { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Event> Events { get; set; }
        public virtual Individual Individual { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<Notification> Notifications1 { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual ICollection<UserEventAttendant> UserEventAttendants { get; set; }
        public virtual ICollection<User> User1 { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
